apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hammerspace-monitoring.fullname" . }}-prometheus
  labels:
    app: {{ include "hammerspace-monitoring.name" . }}
    component: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.config.global.scrape_interval }}
      evaluation_interval: {{ .Values.prometheus.config.global.evaluation_interval }}
      external_labels:
        {{- toYaml .Values.prometheus.config.global.external_labels | nindent 8 }}
      metric_name_validation_scheme: {{ .Values.prometheus.config.global.metric_name_validation_scheme }}

    scrape_configs:
      {{- range $clusterName, $cluster := .Values.prometheus.clusters }}
      - job_name: 'hammerspace-anvil-{{ $clusterName }}'
        static_configs:
          - targets:
            {{- range $cluster.anvil.targets }}
            - '{{ .ip }}:{{ .port }}'
            {{- end }}
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: {{ $cluster.anvil.instance }}

      - job_name: 'hammerspace-dsx-{{ $clusterName }}'
        static_configs:
          - targets:
            {{- range $cluster.dsx.targets }}
            - '{{ .ip }}:{{ .port }}'
            {{- end }}
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: {{ $cluster.dsx.instance }}

      - job_name: 'hammerspace-cluster-{{ $clusterName }}'
        static_configs:
          - targets:
            {{- range $cluster.cluster.targets }}
            {{- range .ports }}
            - '{{ $.ip }}:{{ . }}'
            {{- end }}
            {{- end }}
        relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: '{{ $clusterName }}-cluster'
      {{- end }}
