apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hammerspace-monitoring.fullname" . }}-prometheus-config
  labels:
    app: {{ include "hammerspace-monitoring.name" . }}
    component: prometheus
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        monitor: example
      metric_name_validation_scheme: legacy

    scrape_configs:
      - job_name: prometheus
        fallback_scrape_protocol: PrometheusText1.0.0
        static_configs:
          - targets: ['localhost:9090']
            labels:
              node_type: prometheus

      {{- if .Values.prometheus.scrapeTargets.cluster }}
      - job_name: cluster
        fallback_scrape_protocol: PrometheusText1.0.0
        static_configs:
          - targets:
              {{- range .Values.prometheus.scrapeTargets.cluster }}
              - '{{ . }}'
              {{- end }}
            labels:
              cluster: {{ .Values.prometheus.clusterLabel | default "default-cluster" }}
              node_type: clusterip
              instance: {{ .Values.prometheus.clusterLabel | default "default-cluster" }}
      {{- end }}

      {{- if .Values.prometheus.scrapeTargets.anvil }}
      - job_name: anvil_nodes
        fallback_scrape_protocol: PrometheusText1.0.0
        static_configs:
          - targets:
              {{- range .Values.prometheus.scrapeTargets.anvil }}
              - '{{ . }}'
              {{- end }}
            labels:
              cluster: {{ .Values.prometheus.clusterLabel | default "default-cluster" }}
              node_type: anvil
              instance: {{ .Values.prometheus.anvilInstance | default "default-anvil-instance" }}
      {{- end }}

      {{- if .Values.prometheus.scrapeTargets.dsx }}
      - job_name: dsx_nodes
        fallback_scrape_protocol: PrometheusText1.0.0
        static_configs:
          - targets:
              {{- range .Values.prometheus.scrapeTargets.dsx }}
              - '{{ . }}'
              {{- end }}
            labels:
              cluster: {{ .Values.prometheus.clusterLabel | default "default-cluster" }}
              node_type: dsx
              instance: {{ .Values.prometheus.dsxInstance | default "default-dsx-instance" }}
      {{- end }}
