---
# templates/grafana-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hs-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "hammerspace-monitoring.name" . }}
      component: grafana
  template:
    metadata:
      labels:
        app: {{ include "hammerspace-monitoring.name" . }}
        component: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.adminUser }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.adminPassword }}
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
              subPath: dashboards.yaml
            - name: dashboards
              mountPath: /etc/grafana/provisioning/dashboards
            - name: datasource
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: {{ include "hammerspace-monitoring.fullname" . }}-grafana
        - name: dashboard-provider
          configMap:
            name: {{ include "hammerspace-monitoring.fullname" . }}-dashboard-provider
        - name: dashboards
          configMap:
            name: {{ include "hammerspace-monitoring.fullname" . }}-dashboards
        - name: datasource
          configMap:
            name: {{ include "hammerspace-monitoring.fullname" . }}-datasource