---
# templates/grafana-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hs-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "hammerspace-monitoring.name" . }}
      component: grafana
  template:
    metadata:
      labels:
        app: {{ include "hammerspace-monitoring.name" . }}
        component: grafana
    spec:
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.adminUser }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.adminPassword }}
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            {{- if .Values.dashboards.enabled }}
            - name: dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards
            {{- range $key, $dashboard := .Values.grafana.dashboards }}
            - name: dashboard-{{ $dashboard.name }}
              mountPath: /etc/grafana/provisioning/dashboards/{{ $dashboard.filename }}
              subPath: {{ $dashboard.filename }}
            {{- end }}
            {{- end }}
            - name: datasource
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: {{ include "hammerspace-monitoring.componentName" (list . "grafana") }}
        {{- if .Values.dashboards.enabled }}
        - name: dashboard-provider
          configMap:
            name: {{ include "hammerspace-monitoring.fullname" . }}-dashboard-provider
        {{- range $key, $dashboard := .Values.grafana.dashboards }}
        - name: dashboard-{{ $dashboard.name }}
          configMap:
            name: {{ include "hammerspace-monitoring.fullname" . }}-dashboard-{{ $dashboard.name }}
        {{- end }}
        {{- end }}
        - name: datasource
          configMap:
            name: {{ include "hammerspace-monitoring.fullname" . }}-datasource