{{- if .Values.prometheus.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus
  labels:
    app: {{ include "hammerspace-monitoring.name" . }}
    component: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: prometheus
  apiGroup: rbac.authorization.k8s.io
{{- end }}
