---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: {{ include "hammerspace-monitoring.name" . }}
    component: prometheus
spec:
  type: {{ get (get .Values.prometheus "service" | default (dict "type" "NodePort")) "type" }}
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  selector:
    app: {{ include "hammerspace-monitoring.name" . }}
    component: prometheus

