{{- define "hammerspace-monitoring.pvc" -}}
{{- $root := index . 0 }}
{{- $component := index . 1 }}
{{- $config := index . 2 }}
{{- if $config.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hammerspace-monitoring.componentName" (list $root $component) }}
  labels:
    {{- include "hammerspace-monitoring.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
<<<<<<< HEAD
  accessModes:
    {{- toYaml .Values.grafana.persistence.storage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.storage.size | default "5Gi" }}
  storageClassName: {{ .Values.prometheus.persistence.storage.storageClassName | quote }}
{{- end }}
=======
  accessModes: {{ toYaml $config.persistence.storage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ $config.persistence.storage.size }}
  storageClassName: {{ $config.persistence.storage.storageClassName | quote }}
{{- end }}
{{- end -}}

---
# templates/prometheus-pvc.yaml
{{ include "hammerspace-monitoring.pvc" (list . "prometheus" .Values.prometheus) }}

---
# templates/grafana-pvc.yaml
{{ include "hammerspace-monitoring.pvc" (list . "grafana" .Values.grafana) }}
>>>>>>> 904f132 (added templete update and role binding)
