{{- if .Values.prometheus.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus
  labels:
    app: prometheus
rules: []  # No permissions needed; avoids cluster access
{{- end }}
