{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  labels:
    app: {{ include "hammerspace-monitoring.name" . }}
    component: prometheus
{{- end }}
