# Optional override for naming
nameOverride: ""
fullnameOverride: ""

prometheus:
  persistence:
    enabled: true
    storage:
      accessModes:
        - ReadWriteOnce
      storageClassName: "hs-storage"
      size: 5Gi

  clusterLabel: "boston"
  anvilInstance: "kbk-hs-boston-anvil.onaside.quest.local"
  dsxInstance: "kbk-hs-boston-dsx1.onaside.quest.local"

  scrapeTargets:
    cluster:
      - 10.200.120.200:9101
      - 10.200.120.200:9102
      - 10.200.120.200:9103

    anvil:
      - 10.200.120.200:9100

    dsx:
      - 10.200.120.201:9100
      - 10.200.120.201:9105

grafana:
  adminUser: admin
  adminPassword: admin
  persistence:
    enabled: true
    storage:
      accessModes:
        - ReadWriteOnce
      storageClassName: "hs-storage"
      size: 5Gi

  dashboards:
    hammerspaceFilesystemStats:
      name: hammerspace-filesystem-stats
      filename: hammerspace_filesystem_stats.json
      path: files/dashboards/hammerspace_filesystem_stats.json
    hammerspaceProtocolStats:
      name: hammerspace-protocol-stats
      filename: hammerspace_protocol_stats.json
      path: files/dashboards/hammerspace_protocol_stats.json
    hammerspaceReplication:
      name: hammerspace-replication
      filename: hammerspace_replication.json
      path: files/dashboards/hammerspace_replication.json
    hammerspaceObjectMobility:
      name: hammerspace-object-mobility
      filename: hammerspace_object_mobility.json
      path: files/dashboards/hammerspace_object_mobility.json
    hammerspaceFileMobility:
      name: hammerspace-file-mobility
      filename: hammerspace_file_mobility.json
      path: files/dashboards/hammerspace_file_mobility.json

dashboards:
  enabled: true