# values.yaml
# Optional override for naming
nameOverride: ""
fullnameOverride: ""

prometheus:
  persistence:
    enabled: true
    storage:
      accessModes:
        - ReadWriteOnce
<<<<<<< HEAD
      storageClassName: "hs-storage"
      size: 5Gi
=======
      size: 8Gi
      storageClassName: hs-storage
>>>>>>> 904f132 (added templete update and role binding)

grafana:
  adminUser: admin
  adminPassword: admin
  persistence:
    enabled: true
    storage:
      accessModes:
        - ReadWriteOnce
<<<<<<< HEAD
      storageClassName: "hs-storage"
      size: 5Gi
  dashboards:
    hammerspaceFilesystemStats:
      name: hammerspace-filesystem-stats
      filename: hammerspace_filesystem_stats.json
      path: dashboards/hammerspace_filesystem_stats.json

dashboards:
  enabled: true

=======
      size: 4Gi
      storageClassName: hs-storage
>>>>>>> 904f132 (added templete update and role binding)
