# values.yaml
# Optional override for naming
nameOverride: ""
fullnameOverride: ""

prometheus:
  persistence:
    enabled: true
    storage:
      accessModes:
        - ReadWriteOnce
      storageClassName: "hs-storage"
      size: 5Gi

grafana:
  adminUser: admin
  adminPassword: admin
  persistence:
    enabled: true
    storage:
      accessModes:
        - ReadWriteOnce
      storageClassName: "hs-storage"
      size: 5Gi
  dashboards:
    hammerspaceFilesystemStats:
      name: hammerspace-filesystem-stats
      filename: hammerspace_filesystem_stats.json
      path: dashboards/hammerspace_filesystem_stats.json

dashboards:
  enabled: true

