# Optional override for naming
nameOverride: ""
fullnameOverride: ""

prometheus:
  image:
    repository: prom/prometheus
    tag: v2.45.0
  persistence:
    enabled: true
    storage:
      accessModes:
        - ReadWriteOnce
      storageClassName: "hs-storage"
      size: 5Gi
  config:
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        monitor: example
      metric_name_validation_scheme: legacy

  clusters:
    boston:
      label: "boston"
      anvil:
        instance: "kbk-hs-boston-anvil.onaside.quest.local"
        targets:
          - ip: "10.200.120.200"
            port: 9100
      dsx:
        instance: "kbk-hs-boston-dsx1.onaside.quest.local"
        targets:
          - ip: "10.200.120.201"
            port: 9100
          - ip: "10.200.120.201"
            port: 9105
      cluster:
        targets:
          - ip: "10.200.120.200"
            ports: [9101, 9102, 9103]

grafana:
  image:
    repository: grafana/grafana
    tag: 10.2.0
  adminUser: admin
  adminPassword: admin
  persistence:
    enabled: true
    storage:
      accessModes:
        - ReadWriteOnce
      storageClassName: "hs-storage"
      size: 5Gi
  config:
    dashboardProvider:
      name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /etc/grafana/provisioning/dashboards

  dashboards:
    hammerspaceFilesystemStats:
      name: hammerspace-filesystem-stats
      filename: hammerspace_filesystem_stats.json
      path: files/dashboards/hammerspace_filesystem_stats.json
    hammerspaceProtocolStats:
      name: hammerspace-protocol-stats
      filename: hammerspace_protocol_stats.json
      path: files/dashboards/hammerspace_protocol_stats.json
    hammerspaceReplication:
      name: hammerspace-replication
      filename: hammerspace_replication.json
      path: files/dashboards/hammerspace_replication.json
    hammerspaceObjectMobility:
      name: hammerspace-object-mobility
      filename: hammerspace_object_mobility.json
      path: files/dashboards/hammerspace_object_mobility.json
    hammerspaceFileMobility:
      name: hammerspace-file-mobility
      filename: hammerspace_file_mobility.json
      path: files/dashboards/hammerspace_file_mobility.json

dashboards:
  enabled: true