# Optional override for naming
nameOverride: ""
fullnameOverride: ""

prometheus:
  persistence:
    enabled: true
    storage:
      accessModes:
        - ReadWriteOnce
      storageClassName: "hs-storage"
      size: 5Gi

  clusterLabel: "boston"
  anvilInstance: "kbk-hs-boston-anvil.onaside.quest.local"
  dsxInstance: "kbk-hs-boston-dsx1.onaside.quest.local"

  scrapeTargets:
    cluster:
      - 10.200.120.200:9101
      - 10.200.120.200:9102
      - 10.200.120.200:9103

    anvil:
      - 10.200.120.200:9100

    dsx:
      - 10.200.120.201:9100
      - 10.200.120.201:9105

grafana:
  adminUser: admin
  adminPassword: admin
  persistence:
    enabled: true
    storage:
      accessModes:
        - ReadWriteOnce
      storageClassName: "hs-storage"
      size: 5Gi

  dashboards:
    list:
      - name: hammerspace-filesystem-stats
        filename: hammerspace_filesystem_stats.json
        path: dashboards/hammerspace_filesystem_stats.json
      - name: hammerspace-nodes
        filename: hammerspace_nodes.json
        path: dashboards/hammerspace_nodes.json
      - name: hammerspace-performance
        filename: hammerspace_performance.json
        path: dashboards/hammerspace_performance.json
      - name: hammerspace-alerts
        filename: hammerspace_alerts.json
        path: dashboards/hammerspace_alerts.json
      - name: hammerspace-capacity
        filename: hammerspace_capacity.json
        path: dashboards/hammerspace_capacity.json

dashboards:
  enabled: true